lib/src/chewie_player.dart, lib/src/player_with_controls.dart
remove _onPlay listener from the controller when the widget is disposed and avoid disposing the controller that I'm not the owner of it - the owner is responsible to invoke dispose() (and potentially reuse it ).
=> A fix to allow using the controller between chewie players

lib/src/cupertino_controls.dart
It now really skips 15 seconds as intended
=> Fix skipping

lib/src/chewie_player.dart, pubspec.yaml
This PR will:
- Keep the `video_player` version below 0.6.4 which is fine for video rendering since there is a known issue with 0.6.5 that prevents frames to be shown unless the video enters in full screen and then disposes back to inline.
- Adds a property to choose whether the video should start on full screen or not when the playback starts.
=> resolves video_player version & adds support for starting video on fullscreen 

pubspec.yaml
An updated version of video_player was released on Oct. 17 with some bug fixes. I have upgraded Chewie to support this latest version.
=> Update to video_player >=0.7.0 <0.8.0

lib/src/player_with_controls.dart
Wrapping the player also when in fullscreen preserve the correct aspect ratio of the video. It seems to work well on Android and iOS. Thank you
=> Always wrap player in AspectRatio to preserve aspect ratio in fullscreen

lib/src/chewie_player.dart, lib/src/cupertino_controls.dart, lib/src/material_controls.dart, lib/src/player_with_controls.dart, pubspec.yaml
In this PR I've added two options to hide time and progress bar which is called "isLive" and another one to allow keep device screen on while in full screen (allowedScreenSleep).
Issues: #64 #44
=> Added options for live and screen sleep

example/lib/auto_rotate.dart, example/lib/main.dart, lib/src/chewie_player.dart, lib/src/cupertino_controls.dart, lib/src/cupertino_progress_bar.dart, lib/src/material_controls.dart, lib/src/material_progress_bar.dart
This should make it much better to handle playback errors:
1. No longer shows errors in the progress bar
2. By default, displays an error icon when an error occurs
3. Adds a configurable `errorBuilder` to the ChewieController. If you provide a custom `errorBuilder`, then this function will be used to display a custom error Widget.
To try this branch out, use the following in your pubspec:
```
dependencies:
chewie:
git:
url: git://github.com/brianegan/chewie.git
ref: error-message
```
=> Fixes #114: Better support for playback errors

lib/src/chewie_player.dart
updated the fullScreenByDefault logic to check on initialization and enter fullScreen and then remove the Listener after executing once. This prevents the listener from firing again on user action.
=> fixes #132: only check fullScreenByDefault once

lib/src/player_with_controls.dart
Removes the `Hero` widget from the `player_with_controls.dart` build method to fix #143, allowing Chewie to be used within an external (to Chewie) Hero widget, as you cannot embed Hero widgets.
See: 
- https://github.com/flutter/flutter/issues/1398
- https://github.com/flutter/flutter/pull/28470
=> fixes #143 - remove Hero widget

lib/src/cupertino_controls.dart, lib/src/material_controls.dart
Fixes the issue with pressing the play button when the video is finished. Before the video player would keep playing even if the video has finished. 
This pr relates to what [#88](https://github.com/brianegan/chewie/issues/88) suggested but does not add a replay button icon.
=> fixes #88 - Replay on play when video finished

CHANGELOG.md, lib/src/chewie_player.dart, lib/src/cupertino_controls.dart, pubspec.yaml
The current wakelock plugin (`flutter_screen`) lacks maintenance and has had AndroidX compatibility issues for over half a year.
To fix this, I changed the plugin to `wakelock`, which is also more lightweight because it has just the wakelock and no brightness adjustments.
The formatting `cupertino_controls.dart` is caused by `flutter format` and Pub complained about it before.
The version constraint is correct like this and I will ensure that there are no compatibility changes until `0.2.0` as I am the author of [`wakelock`](https://pub.dev/packages/wakelock).
* Closes #141 (that one is already solved, but including it in this comment will automatically close it upon merging).
https://github.com/clovisnicolas/flutter_screen/pull/15
=> Switch wakelock plugin

lib/src/cupertino_controls.dart, lib/src/material_controls.dart
fixed issue with setting autoPlay to false. The user can now set autoPlay to false and the video will still be loaded. The issue was that durant was null and couldn't render the video. Another future fix would be to display the play button instead of the loading icon when autoPlay is set to false.
=> User can now set autoPlay to false

lib/src/material_progress_bar.dart
When switching to another widget; the video continued to play on the back and wants to report transactions, but the widget failed because it was not mounted.
For this reason, it is provided to check whether the widget is mounted or not.
=> Check widget is mounted

lib/src/cupertino_controls.dart
As already discussed here: https://github.com/brianegan/chewie/issues/387 I have added the new icons to the cupertino controls:
=> feat(cupertino_controls): add new skip icons

pubspec.yaml
@Ahmadre Just want to point out that it is not guaranteed that there will be no breaking changes until `1.0.0`. The Pub versioning would allow breaking changes when upgrading any **x** version in `0.x.y+z` or `x.y.z` when `x > 1`.
It is correct that there was no breaking change for `wakelock 0.2.0` ([changelog](https://pub.dev/packages/wakelock/changelog#020)) - only deprecations. However, I would probably want to remove the deprecations at some point.
---
About the `cupertino_icons` change: the caret syntax is identical in that case and the preferred syntax. See https://dart.dev/tools/pub/dependencies#caret-syntax.
=> Fix dependencies

lib/src/cupertino_controls.dart, lib/src/material_controls.dart
=> Show replay button if video completes for Android OS

lib/chewie.dart
I want to use the `MaterialControls` and `CupertinoControls` in customControls parameter.
> _chewieController = ChewieController(
videoPlayerController: _videoPlayerController,
aspectRatio: 3 / 2,
autoInitialize: true,
customControls: MaterialControls(),
);
Use `MaterialControls` to avoid this problem(https://github.com/brianegan/chewie/issues/354) on iOS.
=> Export controls in chewie.dart.

pubspec.yaml
Since https://github.com/brianegan/chewie/commit/971c97aebaa976e3fd614426becc144d80d5f97a, chewie won't compile with Flutter version lower than 1.22. See https://github.com/flutter/flutter/commit/2032a448edd0da6460250f7d099d324a5989957f for more information. This commit bumps the required version in `pubspec.yaml` so app developers can upgrade their Flutter installation.
=> Bump required Flutter version 1.20 -> 1.22

lib/src/cupertino_controls.dart
Fixes the duration is called on null error which appears when showing videos with cupertino controls.
Associated tickets: 
- https://github.com/brianegan/chewie/issues/229
- https://github.com/brianegan/chewie/issues/360
- https://github.com/brianegan/chewie/issues/306
=> Fix duration called on null for cupertino controls

example/lib/auto_rotate.dart, lib/src/chewie_player.dart
`resizeToAvoidBottomPadding` is deprecated since 1.19 and now removed.
It is replaced by `resizeToAvoidBottomInset `
https://api.flutter.dev/flutter/material/Scaffold/resizeToAvoidBottomPadding.html
=> fixed resizeToAvoidBottomPadding

README.md
IOS simulator now works on  flutter 1.26.0.
=> Remove ios simulator warning

lib/src/animated_play_pause.dart, lib/src/center_play_button.dart, lib/src/cupertino_controls.dart, lib/src/material_controls.dart
This PR adds an `AnimatedPlayPause` widget that encapsulates the animation. It implicitly animates the icon when it is rebuilt with a different `playing` argument.
Both `MaterialControls` and `CupertinoControls` can now simply use this widget without needing an `animationConttroller` on their own.
Screen recording:
https://user-images.githubusercontent.com/44171190/109505643-17a3d880-7a9d-11eb-9227-2dee7cc0862a.mp4
=> Animate all play/pause icons

pubspec.yaml
Updated wakelock because more than one dependency im using is constrained to latest version
=> chore: updated wakelock from 0.4.0 to 0.5.1

lib/src/material_controls.dart
I got the following crash:
```
Null check operator used on a null value
Stack trace:
#0 State.setState (package:flutter/src/widgets/framework.dart:1287)
#1 _MaterialControlsState._updateState (package:chewie_audio/src/material_controls.dart:227)
#2 ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:243)
#3 ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:309)
#4 VideoPlayerController.pause (package:video_player/video_player.dart:405)
#5 _VideoAppLifeCycleObserver.didChangeAppLifecycleState (package:video_player/video_player.dart:584)
#6 WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:690)
#7 ServicesBinding._handleLifecycleMessage (package:flutter/src/services/binding.dart:192)
#8 …
```
=> _MaterialControlState._updateState: check mounted

lib/src/cupertino/cupertino_controls.dart, lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart
Hi!
I applied some changes to support disabling `CenterPlayButton` in the control classes due to #494.
Not sure if it's the best way to resolve that issue. Will be happy to know if it's better to do it in another way.
Regards...
=> Add an option to hide play button

lib/src/chewie_player.dart, lib/src/cupertino/cupertino_controls.dart, lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart
The package always uses rootNavigator for Pushing Fullscreen Page, showing controls popup or bottom sheets, etc. But, there are cases where this behavior is undesirable and cause issues such as popping the wrong page on pressing back button (Especially when using custom navigation/routing packages such as [auto_route](https://pub.dev/packages/auto_route) or nested navigators).
I have added a useRootNavigator property to ChewieController such that the default behavior is same as before but users can configure chewie to not use rootNavigator.
=> Add useRootNavigator property to ChewieController

lib/src/chewie_player.dart, lib/src/player_with_controls.dart
Hi,
This might be (or not!) an interesting feature for Chewie. It allows for zoom and panning in the video window. Please feel free to consider it as a potential feature. 
Zoom/panning and scale factor can be configured from the hosting app side.
Thank you.
=> Allow video zooming with InteractiveViewer widget.

example/lib/app/app.dart, lib/src/chewie_player.dart, lib/src/cupertino/cupertino_controls.dart, lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart
The time interval without user interactions after which the controls are hidden is now customizable.
Negative time intervals are ignored, defaulting to a 3 seconds timer. closes #595
=> Added customizable timer to hide controls

pubspec.yaml
- Dependency was on wrong place and prevented users of this package from upgrading to `very_good_analysis: 3.0.0`
=> chore: Move very_good_analysis to dev_dependencies

example/lib/app/app.dart, lib/src/chewie_player.dart, lib/src/cupertino/cupertino_controls.dart, lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart, lib/src/progress_bar.dart, pubspec.yaml
After a bit of digging in the `video_player`, I managed to enhance the seeking performance.
However, with this when seeking, it's frequent to have dozen of milliseconds between `STATE_BUFFERING` and `STATE_READY`. This makes the `CircularProgressIndicator` be displayed during a few milliseconds.
To prevent this, we propose to introduce a bit of temporization between the first `isBuffering` status and displaying the `CircularProgressIndicator`.
| Proposal | Actual |
| --- | --- |
|![chewie](https://user-images.githubusercontent.com/13080562/161302766-aa750878-96fe-4031-b745-8a65455a2404.gif)|![schnell](https://user-images.githubusercontent.com/13080562/161302775-52139f22-787e-4ed9-8c1a-d106378d89e9.gif)|
Currently, an arbitrary timeout of 200ms has been chosen.
Linked pull request …
=> [Android] Add a delay before displaying progress indicator

lib/src/chewie_player.dart, lib/src/player_with_controls.dart
This simply adds a way to use a TransformationController with the InteractiveViewer inside the player.
=> Add transformationController to Interactive Viewer

example/lib/app/theme.dart, lib/chewie.dart, lib/src/center_play_button.dart, lib/src/cupertino/cupertino_controls.dart, lib/src/helpers/adaptive_controls.dart, lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart, lib/src/material/widgets/playback_speed_dialog.dart, lib/src/player_with_controls.dart
When using Material 3, the AnimatedOpacity of **CenterPlayButton** expands to fill the available space, and looks like this:
This PR fixes it, and in addition:
- It exposes MaterialDesktopControls to allow devs to explicitly use it.
- Some lints fixed for better performance
=> Fix for CenterPlayButton UI bug when using Material 3

.github/workflows/ci.yml, analysis_options.yaml, example/analysis_options.yaml, example/pubspec.yaml, lib/src/chewie_player.dart, lib/src/cupertino/cupertino_controls.dart, lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart, lib/src/material/widgets/playback_speed_dialog.dart, lib/src/models/subtitle_model.dart, lib/src/player_with_controls.dart, pubspec.yaml
Library and Example App are now using `flutter_lints`.
Addresses any outstanding Dart Analysis issues as a result. Mostly just renaming variables.
=> Flutter 3.3 lint fixes

lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart
Due to Flutter 3.7, certain fields are now deprecated.
This fix migrates those particular fields to their current counterparts.
=> Added Dart Analysis fixes due to Flutter 3.7.

lib/src/player_with_controls.dart
Causes usability issues, when controls are similar color as the video
Broken since v1.3.5
| master | fix/overlay |
|--------|--------|
| <img width="482" alt="currently" src="https://user-images.githubusercontent.com/10659247/234490239-343f4977-51a8-48ca-ba79-57b5eb19c000.png"> | <img width="482" alt="fixed" src="https://user-images.githubusercontent.com/10659247/234490280-32cb2595-a8ea-45d8-8862-4ee38c99994a.png"> |
=> Fix overlay not visible

CHANGELOG.md, example/lib/app/app.dart, lib/src/chewie_player.dart, pubspec.yaml
Migrated `wakelock` to `wakelock_plus`. Also upgraded all other dependencies.
Also increased the minimum supported Flutter version to `2.11.0`.
Addresses #729.
=> Wakelock Plus Migration

lib/src/chewie_player.dart
This commit addresses the issue where Chewie will force disable Wakelock without taking into account that other packages / app parts might depend on the same package.
In my case, the screen will be able to sleep again after exiting fullscreen, even though we don't want it to while the player is running.
Edit: If needed, for context as to why I removed the comment above the code. It was relevant over 3 years ago, when "sleep" was replaced with Wakelock and a comment was written to explain why the if statement was removed. Yes, we don't have to check if wakelock is enabled anymore, but we should still check if we were the ones that enabled it and not override any custom implementations an app may have.
=> Stop force disabling wakelock

lib/src/material/widgets/options_dialog.dart, lib/src/progress_bar.dart
This PR fixes issue #789 and the following bugs that were uncovered as a result of fixing it:
- Due to using Duration.zero as an invalid value, the pointer's behavior at the left edge of the progress bar was unnatural. 
- The pointer was able to go beyond the confines of the progress bar.
=> Fix: Progress bar does not follow drag #789

lib/src/player_with_controls.dart
When Chewie wrapped by RotatedBox like this. It is used in the situation that device not support landscape and portrait switch.
```
RotatedBox(quarterTurns: 1,
child: Chewie(
controller: _chewieController!,
))
```
It will not occupy all the space.
Use LayoutBuilder instead of MediaQuery is more adaptive. It looks like this now.
=> fix display size while Chewie wrapped by some rotate widget

CHANGELOG.md, lib/src/chewie_player.dart, lib/src/material/material_desktop_controls.dart, pubspec.yaml
https://github.com/fluttercommunity/chewie/issues/790
https://github.com/fluttercommunity/chewie/issues/688
When viewing full screen on web, returning from full screen causes original video to lose picture.
We re initialise controllers for web only when returning from full screen 
Also refactor un needed set states, refactor play if finished( as video player restarts if finished)
=> [Web] fix exit full screen issue

README.md
Updated VideoPlayerController initialization to use VideoPlayerController.networkUrl(Uri.parse('video_url')), complying with video_player ^2.8.2 guidelines.
Changes :
```dart
final videoPlayerController = VideoPlayerController.network(
'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4'); 
To 
final videoPlayerController = VideoPlayerController.networkUrl(Uri.parse(
'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4'));
=> Refactor VideoPlayerController initialization to adhere to video_player ^2.8.2 guidelines

lib/src/material/material_controls.dart
When a player widget is used inside a scaffold with `extendBodyBehindAppBar` set to **true** on a _Scaffold_, the progress bar and the fullscreen button go out of the player bounds which breaks the layout and makes them inaccessible for a user's input.
`extendBodyBehindAppBar: true`, controls are falling down
`extendBodyBehindAppBar: false`, controls are fine, but we need the content of the screen go under the app bar
`extendBodyBehindAppBar: true`, and the fix from PR
This is how it should work. 
If I got it right the issue is Android/Fucsia related, since MaterialControls do not used for others. This was not tested on Fucsia.
=> Fix the Safe area conflict for material controls in Android

example/lib/app/app.dart, example/pubspec.yaml, lib/src/animated_play_pause.dart, lib/src/center_play_button.dart, lib/src/chewie_player.dart, lib/src/cupertino/cupertino_controls.dart, lib/src/cupertino/cupertino_progress_bar.dart, lib/src/cupertino/widgets/cupertino_options_dialog.dart, lib/src/helpers/adaptive_controls.dart, lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart, lib/src/material/material_progress_bar.dart, lib/src/material/widgets/options_dialog.dart, lib/src/material/widgets/playback_speed_dialog.dart, lib/src/player_with_controls.dart, lib/src/progress_bar.dart, pubspec.yaml
Due to `wakelock_plus` version `1.2.x`, the next minor release will require Flutter `3.19` and Dart `3.3` or higher.
=> Flutter 3.19 enforcement

example/android/app/build.gradle, example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties, example/android/settings.gradle, example/pubspec.yaml, lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart, pubspec.yaml
Update compileSdkVersion and dependencies.
=> package upgrades

lib/chewie.dart, lib/src/cupertino/cupertino_controls.dart, lib/src/cupertino/cupertino_progress_bar.dart, lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart, lib/src/material/material_progress_bar.dart, lib/src/progress_bar.dart
1. Export MaterialVideoProgressBar widget for ChewieController's customControls usage to achieve below ui.
2. Add barHeight and handleHeight properties in MaterialVideoProgressBar widget for height customization.
=> Add barHeight and handleHeight for MaterialVideoProgressBar

lib/src/center_seek_button.dart, lib/src/chewie_player.dart, lib/src/material/material_controls.dart
Adding Forward and Backward seek buttons for Android.
Fixes #615
=> Adding Seek buttons for Android

devtools_options.yaml, example/devtools_options.yaml, example/ios/Runner/AppDelegate.swift, lib/src/cupertino/cupertino_controls.dart, lib/src/helpers/adaptive_controls.dart, lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart
- Add devtools_options.yaml example configuration
- Update iOS AppDelegate.swift
- Fix RTL support in CupertinoControls
- Fix RTL support in MaterialControls
=> - Add devtools_options.yaml configuration files

README.md, example/lib/app/app.dart, lib/src/chewie_player.dart, lib/src/cupertino/cupertino_controls.dart, lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart
Introduced `showSubtitles` in `ChewieController` to allow disabling subtitles by default. Updated controls to respect the flag and aligned behavior across platforms. Added documentation.
Closes #648
=> feat: Add `showSubtitles` flag to control subtitles (#648)

.github/workflows/ci.yml, README.md, lib/src/material/color_compat_extensions.dart, lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart, pubspec.yaml
Library now supports `N-1` minimum Flutter versions. Addresses Issue #888.
=> Fix issue 888

example/lib/app/app.dart, lib/src/cupertino/widgets/cupertino_options_dialog.dart, lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart, lib/src/material/widgets/options_dialog.dart, lib/src/models/option_item.dart
**Fixed pop the wrong page when changing the speed**
Issue: https://github.com/fluttercommunity/chewie/issues/618
This was during the speed change and the use of additional options. This was due to the use of the wrong context. In order for the bottom sheet to close correctly, we need to use the context of the bottom sheet itself.
```
await showModalBottomSheet<OptionItem>(
context: context,
isScrollControlled: true,
useRootNavigator: chewieController.useRootNavigator,
builder: (context) => OptionsDialog(
options: options,
options: _buildOptions(context),
cancelButtonText:
chewieController.optionsTranslation?.cancelButtonText,
),
```
In this regard, I had to add the `BuildContext context` parameter to the `OptionItem` model in `onTap` callback. Now there is no such problem. …
=> Fixed pop the wrong page when changing the speed

.github/workflows/ci.yml, example/lib/app/app.dart, example/lib/main.dart, example/pubspec.yaml, lib/chewie.dart, pubspec.yaml
Added support for Flutter `3.29` while maintaining minimum support for `3.27`.
=> Flutter 3.29 upgrade.

lib/src/chewie_player.dart, lib/src/cupertino/cupertino_controls.dart, lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart
When the video play and the feature enabled one click anywhere on the overlay pause the video
=> Add background tap to pause video feature

README.md, lib/src/cupertino/cupertino_controls.dart, lib/src/helpers/utils.dart, lib/src/material/material_controls.dart, lib/src/material/material_desktop_controls.dart
As already described in multiple issues, there is currently a problem with android reporting "isBuffering" with true even if the video is already playing, preventing the video controls to be displayed. This is a workaround, checking (on android only) if the video is actually buffering. Tested with a network- and file-based video.
>NOTE: This is only a workaround until video_player and flutter is fixed. See https://github.com/flutter/flutter/issues/165149 for more information. Also thanks to @wenwangwill who added a workaround as comment i got inspired from.
If pausing the video and seeking to some point (using seekTo, so clicking on the progress bar) still leads to the infinit loading bar, as no callback is called by the video controller and thus the buffering not updated.
As workaround, …
=> Add workaround for invalid buffering info on android

lib/src/cupertino/cupertino_controls.dart
This pull request includes a small change to the `lib/src/cupertino/cupertino_controls.dart` file. It updates the `_initialize` method to correctly assign the `_subtitleOn` flag based on `chewieController.showSubtitles` and whether the `subtitle` is not empty.
Previously, the code was:
```dart
chewieController.showSubtitles &&
(chewieController.subtitle?.isNotEmpty ?? false);
```
This line had no effects and was effectively dead code. The condition was evaluated but not used.
The updated version assigns the result of the condition to `_subtitleOn`:
```dart
_subtitleOn = chewieController.showSubtitles &&
(chewieController.subtitle?.isNotEmpty ?? false);
```
This change ensures that subtitles are properly enabled by default when the `showSubtitles` flag is true and a non-empty subtitle is …
=> Resolve issue where 'subtitleOn' doesn't enable subtitles by default on iOS
