- README.md
Thanks for this great plugin! Just a small PR to add a link to `video_player`
> Add a link to video_player

- lib/src/utils.dart
> Fix time formatting

- lib/src/chewie_player.dart
Maybe the parameter should be renamed to `startAt`?.
>  Start video at a certain position

- lib/src/cupertino_progress_bar.dart
- lib/src/material_progress_bar.dart
fix this issue: 
https://github.com/brianegan/chewie/issues/113
> fix progress bar goes out while play live stream.

- lib/src/cupertino_controls.dart
Hello
Thanks for the package. There is a rendering bug with the rounded corners of iOS controls (the corners are rounded but there are transparent background below). So my PR is to fix this issue, using the ClipRRect class.
> Fix rounded corners of iOS controls (remove transparent background - using ClipRRect)

- lib/src/chewie_player.dart
- lib/src/cupertino_controls.dart
- lib/src/material_controls.dart
Fixes https://github.com/brianegan/chewie/issues/191
> Add showControlsOnInitialize property

- lib/src/material_controls.dart
tap on video/HitArea hides controls
> Hide material controls on tap on hit area

- CHANGELOG.md
- lib/src/chewie_player.dart
> Remove isInitialRoute from full screen page route

- .gitignore
- lib/src/chewie_player.dart
add an "isPlaying" property and "togglePause" method
> add an "isPlaying" property and a "togglePause" method

- pubspec.yaml
Hi, I have added the latest video_player version in pubspec.yaml because they fixed a bug on loading videos from assets.
> added latest video_player dependency

- .github/workflows/ci.yml
- .github/workflows/release.yml
- example/lib/auto_rotate.dart
- example/lib/main.dart
- lib/src/chewie_player.dart
- lib/src/cupertino_controls.dart
- lib/src/cupertino_progress_bar.dart
- lib/src/material_controls.dart
- lib/src/material_progress_bar.dart
- lib/src/player_with_controls.dart
- lib/src/utils.dart
Currently runs:
- flutter format -l 120 -n . --set-exit-if-changed
checks if there are unformatted files with a line length of 120. My personal favorite. Could remove to change for 80, if necessary.
If we agree on 120, I would reformat the whole code.
- flutter analyze
For linting. I will include either effective_dart or lint package and update the code accordingly.
There is also a release action, which creates a changelog automatically, if we adhere to conventional commits: https://www.conventionalcommits.org/en/v1.0.0/
> CI for format and linting

- lib/src/cupertino_progress_bar.dart
- lib/src/material_progress_bar.dart
- lib/src/progress_bar.dart
Still work in progress, so far I only merged the progress bars: The existing API still exists, but there is now a `VideoProgressBar` widget under the hood that takes a `ChewieProgressBarConfiguration` (for now).
> Merge the Material and Cupertino progress bars

- CHANGELOG.md
- example/pubspec.yaml
- pubspec.yaml
> Fix - upgrade dependencies

- CHANGELOG.md
- example/analysis_options.yaml
- example/lib/app/app.dart
- example/lib/app/theme.dart
- lib/src/center_play_button.dart
- lib/src/chewie_player.dart
- lib/src/cupertino/cupertino_controls.dart
- lib/src/material/material_controls.dart
- lib/src/material/material_desktop_controls.dart
- lib/src/material/material_progress_bar.dart
- lib/src/player_with_controls.dart
- lib/src/progress_bar.dart
- pubspec.yaml
**Fix failed CI / Lint**
**This PR contains:**
> Fix - Lint problems

- CHANGELOG.md
- pubspec.yaml
@Ahmadre I created this PR to update the package in pub.dev
The commit should be: bump version: new-version
**e.g. bump version: 1.2.3**
> bump version: 1.2.3

- example/lib/app/app.dart
- lib/src/chewie_player.dart
Hold fullscreen state when ctrl changes
> Fix full screen listener #266

- lib/src/material/material_controls.dart
Support mute control in android
#537 #526 #517
> feat: support mute control in android

- example/android/app/build.gradle
- example/android/build.gradle
Hello !
Quick pull request to upgrade
* kotlin version
* android compileSdkVersion
in the example. (to make it compile :) )
> Upgrade kotlin version and compileSdkVersion in example

- .github/workflows/ci.yml
- lib/src/chewie_player.dart
- lib/src/cupertino/cupertino_controls.dart
- lib/src/material/material_controls.dart
- lib/src/material/material_desktop_controls.dart
- lib/src/progress_bar.dart
> Dragable progressbar

- example/android/app/build.gradle
- example/android/app/src/main/AndroidManifest.xml
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
Upgraded the example Android app to the latest supported Android and Gradle versions respectively.
> Example Android App Upgrade

- example/pubspec.yaml
- pubspec.yaml
Also updated Flutter minimum SDK to version 3.3.0.
> Updated wakelock_plus to version 1.1.0.

- lib/src/cupertino/cupertino_controls.dart
I have fixed the issue #757 .
Kindly review and merge the code.
> Fixed : Playback speed reset on forwarding video

- pubspec.yaml
Package covers are `provider`, `video_player` and `wakelock_plus`.
> Upgrade chewie's dependency package

- README.md
add video_player import otherwise the VideoPlayerController is not available.
> Update README.md video_player import

- example/lib/app/app.dart
Fix `Unsupported operation: Platform._operatingSystem`
> Fix example on web
